### ISSUE TITLE
FSP Proposal Feedback

### ISSUE THREAD

**Issue by andywynkoop** [steveninouye/iBuy#1]
Hey I, nice job on the proposal so far – here are a few changes I'd like you to make: 
- [x] The live link on your home page should say "iBuy Live" instead, this link will eventually point to your heroku-hosted address but linking to the wiki is good for now
# MVP List
- [x] Don't forget to add time estimates for each of your MVPs – these don't have to be completely accurate, just a way for you to budget your time and keep yourself on track
- [x] I would recommend describing each feature as a "user story", describing the behavior of the app from the user's perspective. For instance, instead of "Rails validates uniqueness of username", say "Users cannot sign up with the same username twice". You can also leave off technical details about how the features are implemented, and replace them with expected behavior: Instead of: "Rails ensures that session_token is unique", use: "User's can log in with a unique username and password" and "users remain logged in on page refreshes and subsequent page visits"
- [x] Other core features of this MVP that you should include are: error handling/rendering (session errors, etc), bug-free navigation, adequate styling (to match eBay)
## Product search
- [x] Looking at your schema, it looks like you plan to store product/listing details on the backend. I think this is correct, but I think that the first MVP you do after user auth should be Listing Creation (before implementing search) since you'll need to have listings before you can search them. You should start by building a feature that allows users to create/update/delete listings (CRUD feature) and use a simple index route to display all listings (which will eventually become your search MVP). You can then use eBay's API to seed listing data into your database if you'd like.
- [x] For this MVP, you can display 'current price' as a static field until you implement bidding
- [x] Your search feature should only worry about handling searching by title (for now) and also filter out items with a 'sell_by' date before the current date
## Bidding
- [x] Add more details about what types of validations/ errors apply to this feature (timestamp, amount, etc)
- [x] To summarize, Listings (including product details) and Search should be your first two MVPs, followed by bids, and finally, user profile. I think that implementing the MVPs this way will give you really good experience building out the core functionality of eBay, which is essentially an e-commerce platform with a unique purchasing method (bids). As I mentioned earlier, you can use the API to simulate real listings in your seeds, but your site should function entirely independently from any API data.

# Schema
- [x] You probably don't need to store the user's `location` – if your plan is to use it for search purposes, a better solution might be to use the built-in [geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API), but this should probably be a bonus add-on.
- [x] You should also hold off on adding location to the products/listings table until you're ready to implement that feature (unless you plan to have it displayed in the show page, in which case you can use SF as a default)
- [x] 'Buy it now' should also be a bonus feature
- [ ] I don't think you need a separate table for watches – this collection should be calculated based on existing bids for the current user along with however you choose to represent purchased items (possibly a `purchases` table
- [x] Categories should be a bonus feature
- [x] Don't worry about creating a `photos` table placeholder – just use AWS when you get there

# API routes
- [x] Don't worry about patch, delete for users (yet)
- [x] Add routes for bids (at least post/delete)

# Frontend Routes
- [x] Show page for items (and possibly a bid form page if it isn't nested under the show page

Let me know if you have any questions – if you want we can set up a meeting sometime tomorrow to discuss!

**Comment by steveninouye** [comment]
Watches is a table that logs all the products a user is watching (not bidding on or purchasing).  This is a super far stretch goal and probably won't be implemented in the time that I have but it is a pretty big feature in eBay ( I use it a lot ;-) haha)

Thank you so much for your feedback.  Really thank you.  I can tell you put a lot of time into it.  At anytime, feel free to send more feedback.
