### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by steveninouye** [steveninouye/iBuy#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [ ] Styling
- [x] Smooth, bug-free navigation
- [x] User can log in
- [x] User can log out
- [x] Feedback is displayed to the user (login/sign up errors)
- [x] Errors are cleared when user navigates to a different page
- [x] User remains logged in when refreshing the page
- [x] Links work appropriately
- [x] User is unable to navigate to sign in/sign up form after being logged in
- [x] User's password is a minimum of 6 characters
- [x] Username has to be unique
- [x] User have a option of a demo login

**Comment by andywynkoop** [comment]
- [x] This is looking great so far!
- [x] The favicon is a nice touch
- [x] icons for facebook and google buttons should be the same size
- [x] For those right-side buttons: no border radius, and about 10px more padding - colors, styling and transitions should match ebay's exactly
- [x] Remove colons from placeholder values in session inputs
- [x] `hr` should be a little lighter grey
- [x] nav bar should span the entire screen, not just inner container
- [ ] but the create account link should be somewhere in this form (maybe in the top sentence along with the demo account)
- [x] going to a random route, `/fsafas`, should redirect to `/` or render a 404 page
- [x] all nav links should be styled with `cursor: pointer` (even if they don't do anything yet)
- [x] same for the placeholder category links
