### ISSUE TITLE
Complete Case Insensitve Search Functionality

### ISSUE THREAD

**Issue by steveninouye** [steveninouye/iBuy#3]
- [x] User can search for products by title
- [x] Search results are case insensitive
- [x] Product table has title indexed for faster search queries
- [x] Styling... awesome!
- [x] UI/UX gives feedback to user that their search submission was received (spinner/loading bar)
- [x] If no results are found it tells the user there are no results
- [x] Search results displays no image photo if there is no photo attached to product
- [x] Search results displays title, description, time left until bidding ends, photo, current price, buy-it-now price, and (not stored) product review
- [x] URL saves search submission so that user can revisit the search query at a later time
- [x] Page renders results for a random amount of results
- [x] Page renders an awesome App Academy advertisement LOL
- [x] Search prevents from SQL injection

**Comment by steveninouye** [comment]
```ruby
class API::ProductsController
  before_action :ensure_search_input, only [:index]

  def index
      query = params[:search][:query].gsub(";", " ")
      @products = Product.includes(:bids).with_attached_photos.where("LOWER(title) LIKE ?", "%#{query.downcase}%").limit(50)
  end

  private
  def ensure_search_input
     params[:search] ||= {query: "  "} end
  end
```

**Comment by andywynkoop** [comment]
this looks great! I love the panda
